overwatchapp/config/routes.rb
Rails.application.routes.draw do
  resources :team_compositions
  resources :teams
  resources :users
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"

  resources :users do
    resources :teams, only: [:new, :create]
  end

  resources :teams do
    resources :team_compositions, only: [:new, :create]
  end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

overwatchapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

overwatchapp/app/models/character.rb
class Character < ApplicationRecord
    has_many :team_composition_characters
    has_many :team_compositions, through: :team_composition_characters
end

overwatchapp/app/models/team.rb
class Team < ApplicationRecord
    has_many :team_compositions
    has_many :user_teams
    has_many :users, through: :user_teams
end

overwatchapp/app/models/team_composition.rb
class TeamComposition < ApplicationRecord
    belongs_to :team
    has_many :team_composition_characters
    has_many :characters, through: :team_composition_characters
end

overwatchapp/app/models/team_composition_character.rb
class TeamCompositionCharacter < ApplicationRecord
    belongs_to :team_composition
    belongs_to :character
end

overwatchapp/app/models/user.rb
class User < ApplicationRecord
    has_many :user_teams
    has_many :teams, through: :user_teams
    has_secure_password
    validates :username, presence: true
    validates :username, uniqueness: true

end

overwatchapp/app/models/user_team.rb
class UserTeam < ApplicationRecord
    belongs_to :team 
    belongs_to :user
end

overwatchapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def logged_in?
        !!current_user
    end

    private
        def current_user
            @current_user ||= User.find(session[:user_id]) if session[:user_id]
        end

        def logged_in?
            !!current_user
        end
end

overwatchapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        if logged_in?
            redirect_to user_path(current_user)
        else
            @user = User.new
        end
    end

    def create
        @user = User.find_by(username: params[:user][:username])
        if @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to login_path
    end

end

overwatchapp/app/controllers/team_compositions_controller.rb
class TeamCompositionsController < ApplicationController

    def index
        @comps = TeamComposition.all
    end

    def show
        @comp = TeamComposition.find(params[:id])
    end

    def new
        @comp = TeamComposition.new
        @team = Team.find(params[:team_id])
        @chars = Character.all
    end

    def create
        @comp = TeamComposition.create(comp_params)
        @comp.team = Team.find(params[:team_id])
        raise params
        if @comp.save
            redirect_to team_composition_path(@comp)
        else
            render new_team_composition_path
        end
    end

    private

    def comp_params
        params.require(:team_composition).permit(:notes, :name, :character_ids => [])
    end
end

overwatchapp/app/controllers/teams_controller.rb
class TeamsController < ApplicationController

    def index
        @teams = Team.all 
    end

    def show
        @team = Team.find(params[:id])
    end

    def new
        @team = Team.new
        @user = User.find(params[:user_id])
        @users = User.all
    end

    def create
        @team = Team.create(team_params)
        @user = User.find(params[:user_id])
        if @team.save
            redirect_to team_path(@team)
        else
            render new_team_path
        end
    end

    def edit
        @team = Team.find(params[:id])
    end

    def update
        @team = Team.find(params[:id])
        @team.update(team_params)
        redirect_to team_path(@team)
    end

    private

    def team_params
        params.require(:team).permit(:name, :user_ids => [])
    end
end

overwatchapp/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
      @user = User.create(user_params)
      if @user.id != nil && @user.valid?
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        render new_user_path
      end
    end

    def show
        @user = User.find(params[:id])
        @teams = @user.teams
    end

    def index
        @users = User.all 
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

overwatchapp/app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def add_logout_button
        if logged_in?
            link_to "Log Out", logout_path, method: :delete
        end
    end
end

overwatchapp/app/helpers/sessions_helper.rb
module SessionsHelper
end

overwatchapp/app/helpers/team_compositions_helper.rb
module TeamCompositionsHelper
end

overwatchapp/app/helpers/teams_helper.rb
module TeamsHelper
end

overwatchapp/app/helpers/users_helper.rb
module UsersHelper
end

overwatchapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overwatchapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= add_logout_button %>
    <%= yield %>
  </body>
</html>

overwatchapp/app/views/team_compositions/index.html.erb
<% @comps.each do |comp| %>
<%= comp.name @comp.notes %>
<% end %>

overwatchapp/app/views/team_compositions/new.html.erb
<h2>Create A New Team Comp</h2>
<% if @comp.errors.any? %>
    <div id="error_explanation">
        <ul>
        <% error_messages = @comp.errors.full_messages.uniq %>
        <% error_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>
<%= form_for @comp, url: team_team_compositions_path(@team) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :notes %>
<%= f.text_area :notes %>
<li><%= f.select :character_ids, Character.all.collect {|c| [c.name, c.id]}, {:prompt => "Please select"}, {:multiple => true, :size => 6, :name => 'team_composition[character_ids][]' }%>
<%= f.submit "Create Team Comp"%>
<% end %>

overwatchapp/app/views/team_compositions/show.html.erb
<%= @comp.name %> 
<%= @comp.notes%>
<% @comp.characters.each do |char| %>
<%= char.name %>
<% end %>

overwatchapp/app/views/users/index.html.erb
<% @users.each do |user| %>
    <%= link_to user.username, user_path(user) unless user.username == nil%>
<% end %>

overwatchapp/app/views/users/new.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <ul>
        <% error_messages = @user.errors.full_messages.uniq %>
        <% error_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<%= form_for @user, controller: 'users', action: 'create' do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password%>
    <%= f.password_field :password%>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation%>
    
    <%= f.submit %>
<% end %>

overwatchapp/app/views/users/show.html.erb
<h1>Hello <%=@user.username%>! </h1>
<br>
<h3>My Teams</h3>
<% if @teams == []%>
    <p>You do not belong to any teams</p>
<% else %>
    <% @teams.each do |team| %>
        <li><%= link_to team.name, team_path(team) unless team.name == nil %>
    <% end %>
<% end %>
<br>
<%= link_to "Create Team", new_user_team_path(@user) %>
<br>